FROM mcr.microsoft.com/playwright/python:v1.55.0-jammy

WORKDIR /src

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./src ./src
ENV PYTHONPATH=/src

CMD ["python", "-m", "worker.worker"]
