FROM python:3.11-slim

WORKDIR /src

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt \
 && pip install --no-cache-dir "playwright>=1.47" \
 && playwright install-deps chromium \
 && playwright install chromium

COPY ./src ./src
ENV PYTHONPATH=/src
CMD ["python", "-m", "worker.worker"]
